@endpoint=http://localhost:{{$dotenv PORT}}
@city=city=Paris
@date_start=date_start=2023-11-11T00:00:00.000Z
@date_end=date_end=2025-11-29T23:59:59.000Z
@animal_label=animal_label=Chien
@mobility=mobility=true
@home=home=false


GET {{endpoint}}/api/announcements/highlight

###

GET {{endpoint}}/api/announcements?{{city}}&{{date_start}}&{{date_end}}&{{animal_label}}


###

POST {{endpoint}}/api/users/
Content-Type: application/json

{
  "firstname": "jhon",
  "lastname": "doe",
  "email": "jhon.doe@fake.net",
  "password": "2Aa!4Zz!",
  "city": "quelquepart",
  "phoneNumber": "0610256389",
  "repeatPassword": "2Aa!4Zo!"
}


###



POST {{endpoint}}/api/users/login
Content-Type: application/json

{
  "email": "jhon.doe@fake.net",
  "password": "2Aa!4Zz!"
}

###


GET {{endpoint}}/api/announcements/3

###

PATCH {{endpoint}}/api/announcements/3
Content-Type: application/json

{
  "date_start": "2024-11-11",
  "date_end": "2024-11-29",
  "description": "J'adore m'occuper des gros reptiles",
  "home" : true,
  "mobility" : true
}

###

DELETE {{endpoint}}/api/announcements/2

###

POST {{endpoint}}/api/announcements/
Content-Type: application/json

{
    "date_start": "2024-07-20",
    "date_end": "2024-07-30",
    "mobility": true,
    "home": false,
    "description": "PetSitting",
    "animal": ["Chien", "Chat"]
}
