@endpoint=http://localhost:{{$dotenv PORT}}
@city=city=Lyon
@date_start=date_start=2023-11-11
@date_end=date_end=2025-11-29
@animal_label=animal_label=Poisson rouge


GET {{endpoint}}/api/announcements/highlight

###

GET {{endpoint}}/api/announcements?{{city}}&{{date_start}}&{{date_end}}&{{animal_label}}


###

POST {{endpoint}}/api/users/signin
Content-Type: application/json

{
  "firstname": "Harley",
  "lastname": "Quinn",
  "email": "batou@anonyme.bat",
  "password": "uuUU**00",
  "city": "Gotham City",
  "phone_number": "0612256378",
  "repeatPassword": "uuUU**00"
}
###

POST {{endpoint}}/api/users/login
Content-Type: application/json

{
  "email": "Joker4@anonyme.bat",
  "password": "uuUU**00"
}
###

GET {{endpoint}}/api/users/26
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTk5MzM2ODUsImRhdGEiOnsiaWQiOjIsImZpcnN0bmFtZSI6ImpoaW4iLCJsYXN0bmFtZSI6ImRvdSIsImZpbmdlcnByaW50Ijp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsInVzZXJBZ2VudCI6InZzY29kZS1yZXN0Y2xpZW50In19LCJpYXQiOjE3MTk5MzM2MjR9.2jh-Qfn7grDh5F0fG0G3uAhaVOYqggIr9m3IwIoo4SI
###


GET {{endpoint}}/api/announcements/20

###

PATCH {{endpoint}}/api/announcements/20
Content-Type: application/json

{
  "date_start": "2024-11-11",
  "date_end": "2024-11-29",
  "description": "J'adore m'occuper des gros lezards",
  "home" : true,
  "mobility" : true
}

###

DELETE {{endpoint}}/api/announcements/840

###

PATCH {{endpoint}}/api/users/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjAwNzkwNDQsImRhdGEiOnsiaWQiOjI3LCJmaXJzdG5hbWUiOiJ0ZXN0IiwibGFzdG5hbWUiOiJ0ZXN0IiwiZmluZ2VycHJpbnQiOnsiaXAiOiI6OmZmZmY6MTI3LjAuMC4xIiwidXNlckFnZW50IjoidnNjb2RlLXJlc3RjbGllbnQifX0sImlhdCI6MTcyMDA3ODk4M30.h3qZzpNzSyH6IBlh5MsIw5DBt4EbCGFDCO60ZEGWbe8

{
  "firstname": "PrénomTest",
  "lastname": "NomTest",
  "email": "test.test4@example.com",
  "password": "2Aa!4Zz!1",
  "city": "quelquepart",
  "phone_number": "0610254389",
  "repeatPassword": "2Aa!4Zz!1"
}

###
POST {{endpoint}}/api/announcements/
Content-Type: application/json

{
    "date_start": "2024-07-20",
    "date_end": "2024-07-30",
    "mobility": true,
    "home": false,
    "description": "PetSitting",
    "animal": ["Chien", "Chat"]
}
###

DELETE {{endpoint}}/api/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTk5MzY1MjYsImRhdGEiOnsiaWQiOjIsImZpcnN0bmFtZSI6ImpoaW4iLCJsYXN0bmFtZSI6ImRvdSIsImZpbmdlcnByaW50Ijp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsInVzZXJBZ2VudCI6InZzY29kZS1yZXN0Y2xpZW50In19LCJpYXQiOjE3MTk5MzY0NjZ9.0ZsDWMsLk4tQ7a9zDOst-bOS3fgD6VHEIGipT1ATevQ
