@endpoint=http://localhost:{{$dotenv PORT}}
@department_label=department_label=var
@date_start=date_start=2024-07-20
@date_end=date_end=2025-07-29
@animal_label=animal_label=Chien
@refreshToken = 


GET {{endpoint}}/api/announcements/highlight

###

GET {{endpoint}}/api/announcements?{{department_label}}&{{date_start}}&{{date_end}}&{{animal_label}}


###
GET {{endpoint}/api/announcements}

###
POST {{endpoint}}/api/users/signin
Content-Type: application/json

{
  "firstname": "Harley",
  "lastname": "Quinn",
  "email": "batou@anonyme.bat",
  "password": "uuUU**00",
  "city": "toulon",
  "phone_number": "0612256389",
  "repeatPassword": "uuUU**00",
  "department_label": "var"

}
###

POST {{endpoint}}/api/users/login
Content-Type: application/json

{

  "email": "batou@anonyme.bat",
  "password": "uuUU**00"
}
###

POST {{endpoint}}/api/users/logout/28
# Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjExMzgzNjUsImRhdGEiOnsiaWQiOjI4LCJmaXJzdG5hbWUiOiJIYXJsZXkiLCJmaW5nZXJwcmludCI6eyJpcCI6Ijo6ZmZmZjoxMjcuMC4wLjEiLCJ1c2VyQWdlbnQiOiJ2c2NvZGUtcmVzdGNsaWVudCJ9fSwiaWF0IjoxNzIxMTI0ODY1fQ.V3iHY7h-B4mFFHwaP8FU1iZanaoqrnySqP2151kjRG4


###

GET {{endpoint}}/api/users/28
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjExMzczNjYsImRhdGEiOnsiaWQiOjI4LCJmaXJzdG5hbWUiOiJIYXJsZXkiLCJmaW5nZXJwcmludCI6eyJpcCI6Ijo6ZmZmZjoxMjcuMC4wLjEiLCJ1c2VyQWdlbnQiOiJ2c2NvZGUtcmVzdGNsaWVudCJ9fSwiaWF0IjoxNzIxMTIzODY1fQ.c5EX1tPpYduzxMdW0BGEkIpS-Bhc-aTL7vLBdZDGWrw
Cookie: refreshToken=; expires=Thu, 01 Jan 1970 00:00:00 GMT

###


GET {{endpoint}}/api/announcements/3
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjA0MjYyMzcsImRhdGEiOnsiaWQiOjExLCJmaXJzdG5hbWUiOiJIYXJsZXkiLCJsYXN0bmFtZSI6IlF1aW5uIiwiZmluZ2VycHJpbnQiOnsiaXAiOiI6OmZmZmY6MTI3LjAuMC4xIiwidXNlckFnZW50IjoidnNjb2RlLXJlc3RjbGllbnQifX0sImlhdCI6MTcyMDQyMjYzNn0.12G563LA6o3JRopJbGcD4SmSeONnbWggQ9b5ufYmjU0

###

PATCH {{endpoint}}/api/announcements/20
Content-Type: application/json

{
  "date_start": "2024-11-11",
  "date_end": "2024-11-29",
  "description": "J'adore m'occuper des gros lezards",
  "home" : true,
  "mobility" : true
}

###

DELETE {{endpoint}}/api/announcements/840

###

PATCH {{endpoint}}/api/users/44
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjAwNzkwNDQsImRhdGEiOnsiaWQiOjI3LCJmaXJzdG5hbWUiOiJ0ZXN0IiwibGFzdG5hbWUiOiJ0ZXN0IiwiZmluZ2VycHJpbnQiOnsiaXAiOiI6OmZmZmY6MTI3LjAuMC4xIiwidXNlckFnZW50IjoidnNjb2RlLXJlc3RjbGllbnQifX0sImlhdCI6MTcyMDA3ODk4M30.h3qZzpNzSyH6IBlh5MsIw5DBt4EbCGFDCO60ZEGWbe8

{
  "firstname": "Robert",
  "lastname": "Patulacci",
  "email": "yannbenet@test.com",
  "password": "aaAA!!00",
  "city": "poissy",
  "phone_number": "0612256344",
  "repeatPassword": "aaAA!!00",
  "department_label": "yvelines"
}

###

POST {{endpoint}}/api/announcements/users/28
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjExMzYzNTksImRhdGEiOnsiaWQiOjI4LCJmaXJzdG5hbWUiOiJIYXJsZXkiLCJmaW5nZXJwcmludCI6eyJpcCI6Ijo6ZmZmZjoxMjcuMC4wLjEiLCJ1c2VyQWdlbnQiOiJ2c2NvZGUtcmVzdGNsaWVudCJ9fSwiaWF0IjoxNzIxMTIyODU4fQ.zyQM0EjaWk4zYnd0qTHwNDHgHrm5pA_a3qIjfLWekwM


{
    "date_start": "2024-07-20",
    "date_end": "2025-07-30",
    "mobility": true,
    "home": false,
    "description": "Ceci est une description",
    "animal": ["Chien", "Chat"]
}
###

GET {{endpoint}}/api/users/1/announcements
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjA3ODQ3OTcsImRhdGEiOnsiaWQiOjEsImZpcnN0bmFtZSI6IkhhcmxleSIsImZpbmdlcnByaW50Ijp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsInVzZXJBZ2VudCI6InZzY29kZS1yZXN0Y2xpZW50In19LCJpYXQiOjE3MjA3NzEyOTd9.DKiXpashkxOsuovQAdnst3ovatzny2Qdn7CauKoAGMY
###

DELETE {{endpoint}}/api/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTk5MzY1MjYsImRhdGEiOnsiaWQiOjIsImZpcnN0bmFtZSI6ImpoaW4iLCJsYXN0bmFtZSI6ImRvdSIsImZpbmdlcnByaW50Ijp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsInVzZXJBZ2VudCI6InZzY29kZS1yZXN0Y2xpZW50In19LCJpYXQiOjE3MTk5MzY0NjZ9.0ZsDWMsLk4tQ7a9zDOst-bOS3fgD6VHEIGipT1ATevQ